language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t alexdanila/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true alexdanila/docker-react npm run test